name: rss

on:
  schedule:
    - cron: "*/15 * * * *"
jobs:
  front-rss-bot:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: configure
        run: |
          git config --global user.name "w4ctech"
          git config --global user.email "w3ctech@qq.com"
      - name: working
        run: cd server && npm install && node once.js
