name: Mirror to Gitee Repo

on: [ push, delete, create ]

jobs:
  git-mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Configure Private Key
        run: |
          git config --global user.name "w4ctech"
          git config --global user.email "w3ctech@qq.com"
      - name: Push Mirror
        env:
          SOURCE_REPO: 'https://github.com/w4ctech/front-end-rss.git'
          DESTINATION_REPO: 'git@gitee.com:w4ctech/front-end-rss.git'
        run: |
          git clone https://github.com/w4ctech/front-end-rss.git front-end-rss && cd front-end-rss
          git remote set-url --push origin git@gitee.com:w4ctech/front-end-rss.git
          git fetch -p origin
          git for-each-ref --format 'delete %(refname)' refs/pull | git update-ref --stdin
          git push --mirror
