name: synchro

on: [ push, delete, create ]

jobs:
  git-mirror:
    runs-on: ubuntu-latest
    steps:
      - name: config
        run: |
          git config --global user.name "w4ctech"
          git config --global user.email "w3ctech@qq.com"
      - name: Push
        run: |
          git clone https://github.com/w4ctech/front-end-rss.git front-end-rss && cd front-end-rss
          git branch -m master old-master
          git branch -m main
          git remote set-url --add origin https://gitee.com/w4ctech/front-end-rss.git
          git push origin main
